version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/mysql:5.7.17
          environment:
            - MYSQL_HOST=127.0.0.1
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=exchange_resource_test
            - MYSQL_USER=root
    working_directory: ~/exchange_resource
    steps:
      - checkout
      - attach_workspace:
          at: ~/exchange_resource
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/exchange_resource/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

  rake_test:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/mysql:5.7.17
    working_directory: ~/exchange_resource
    steps:
      - checkout
      - attach_workspace:
          at: ~/exchange_resource
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rake

  precompile_assets:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/mysql:5.7.17
    working_directory: ~/exchange_resource
    steps:
      - checkout
      - attach_workspace:
          at: ~/exchange_resource
      - run: bundle --path vendor/bundle
      - run:
          name: Precompile assets
          command: bundle exec rake assets:precompile
      - persist_to_workspace:
          root: .
          paths: public/assets

  
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - rake_test:
          requires:
            - build
      - precompile_assets:
          requires:
            - build
      
