default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: exchange_resource_development
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: 3306
  username: <%= ENV["USERNAME"]%>
  password: <%= ENV["PASSWORD"]%>

test:
  <<: *default
  database: exchange_resource_test
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: 3306
  username: <%= ENV["USERNAME"]%>
  password: <%= ENV["PASSWORD"]%>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  port: 3306
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
